"""initial_schema_with_razorpay_fields

Revision ID: 90381112911c
Revises: 
Create Date: 2026-04-05 14:30:59.401474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90381112911c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True))
    op.drop_column('subscriptions', 'razorpay_payment_id')
    op.drop_column('subscriptions', 'razorpay_order_id')
    op.drop_column('subscriptions', 'razorpay_customer_id')
    # ### end Alembic commands ###
